services:
  diary:
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10
    restart: always