# Generated by Django 5.1 on 2024-09-04 17:15

import diaryapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("programming_language", "Язык программирования"),
                            ("technology", "Технология"),
                            ("science", "Наука"),
                            ("paradigm", "Парадигма"),
                            ("method", "Метод"),
                            ("Framework", "Фреймворк"),
                            ("library", "Библиотека"),
                            ("language", "Язык"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("beginner", "Базовый"),
                            ("middle", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="0",
                        max_length=8,
                    ),
                ),
                (
                    "experience",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", models.JSONField(default=diaryapp.models.params_factory)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=100,
                        validators=[diaryapp.models.is_resource_available],
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ultimate", "UT"),
                            ("story", "Сюжет"),
                            ("additional", "Дополнение"),
                            ("task", "Задача"),
                        ],
                        default="task",
                        max_length=10,
                    ),
                ),
                ("over_at", models.DateTimeField(null=True)),
                (
                    "planned_datetime",
                    models.DateTimeField(
                        null=True, validators=[diaryapp.models.future_date]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("process", "В процессе"),
                            ("done", "Выполнено"),
                            ("failed", "Провалено"),
                            ("canceled", "Отменено"),
                        ],
                        default="process",
                        max_length=8,
                    ),
                ),
                (
                    "group_priority",
                    models.IntegerField(
                        default=0, help_text="priority grouped by type"
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        help_text="user condition for determining the task status",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="free textarea with any description", max_length=1000
                    ),
                ),
                ("file", models.FileField(upload_to="tasks/attachments")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=15)),
                ("file", models.FileField(null=True, upload_to="books")),
                (
                    "comprehension",
                    models.CharField(
                        choices=[
                            ("unknown", "Неизвестно"),
                            ("0", "0"),
                            ("some", "Некоторое"),
                            ("volume", "Объёмное"),
                            ("full", "Полное"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("author", "name")},
            },
        ),
    ]
