# Generated by Django 5.1 on 2024-08-27 16:48

import diaryapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "dairyapp_day",
            },
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_extracted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "actual"), ("f", "frozen")],
                        default="a",
                        max_length=1,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "db_table": "dairyapp_origin",
                "ordering": ("last_extracted_at", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_update", models.DateTimeField(null=True)),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                ("deprecated_total_tasks", models.SmallIntegerField(default=0)),
                (
                    "deprecated_total_completed_tasks",
                    models.SmallIntegerField(default=0),
                ),
                (
                    "deprecated_complete_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "deprecated_knowledge",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diaryapp.origin",
                    ),
                ),
            ],
            options={
                "db_table": "dairyapp_quest",
                "ordering": ("completed_at", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[diaryapp.models.problem_types_validator],
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="diaryapp.quest",
                    ),
                ),
            ],
            options={
                "db_table": "dairyapp_problem",
            },
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[diaryapp.models.knowledge_types_validator],
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="diaryapp.quest",
                    ),
                ),
            ],
            options={
                "db_table": "dairyapp_knowledge",
            },
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[diaryapp.models.error_types_validator],
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="diaryapp.quest",
                    ),
                ),
            ],
            options={
                "db_table": "dairyapp_error",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        max_length=50, validators=[diaryapp.models.task_types_validator]
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="diaryapp.quest",
                    ),
                ),
            ],
            options={
                "db_table": "dairyapp_task",
            },
        ),
    ]
