# Generated by Django 5.0.7 on 2024-08-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaryapp.origin",
            ),
        ),
    ]
