# Generated by Django 5.0.7 on 2024-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0004_remove_quest_day_alter_quest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="quest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
