# Generated by Django 5.0.7 on 2024-08-23 06:29

import diaryapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "diaryapp",
            "0011_rename_total_completed_tasks_quest_deprecated_total_completed_tasks_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="done",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="knowledge",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="problems",
        ),
        migrations.CreateModel(
            name="Done",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="done",
                        to="diaryapp.quest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Errors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50,
                        validators=[diaryapp.models.error_types_validator],
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="diaryapp.quest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="diaryapp.quest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="diaryapp.quest",
                    ),
                ),
            ],
        ),
    ]
