# Generated by Django 5.0.7 on 2024-08-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0013_alter_errors_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errors",
            name="quest",
            field=models.ForeignKey(
                default=72,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="diaryapp.quest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="errors",
            name="text",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="knowledge",
            name="quest",
            field=models.ForeignKey(
                default=72,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge",
                to="diaryapp.quest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="knowledge",
            name="text",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="problems",
            name="quest",
            field=models.ForeignKey(
                default=72,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="diaryapp.quest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="problems",
            name="text",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
