# Generated by Django 5.0.7 on 2024-08-25 07:58

import diaryapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaryapp", "0017_done_type_knowledge_type_problem_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="theme_description",
        ),
        migrations.AddField(
            model_name="quest",
            name="theme",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        max_length=50, validators=[diaryapp.models.task_types_validator]
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="diaryapp.quest",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Done",
        ),
    ]
