# Generated by Django 5.0.7 on 2024-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairyapp", "0005_alter_day_created_at_alter_quest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="errors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="quest",
            name="theme_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="total_completed_tasks",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quest",
            name="total_tasks",
            field=models.SmallIntegerField(default=0),
        ),
    ]
