# Generated by Django 5.0.7 on 2024-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairyapp", "0006_quest_errors_quest_theme_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="knowledge",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
