# Generated by Django 5.0.7 on 2024-08-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dairyapp", "0014_alter_errors_quest_alter_errors_text_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Errors",
            new_name="Error",
        ),
        migrations.RenameModel(
            old_name="Problems",
            new_name="Problem",
        ),
    ]
