# Generated by Django 5.0.7 on 2024-08-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairyapp", "0015_rename_errors_error_rename_problems_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="done",
            name="quest",
            field=models.ForeignKey(
                default=72,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="done",
                to="dairyapp.quest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="done",
            name="text",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
