# Generated by Django 5.0.7 on 2024-08-24 07:05

import dairyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairyapp", "0016_alter_done_quest_alter_done_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="done",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[dairyapp.models.task_types_validator],
            ),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[dairyapp.models.knowledge_types_validator],
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[dairyapp.models.problem_types_validator],
            ),
        ),
    ]
